Fix bug introduced in r676.
Traceback (most recent call last):
  File "launcher.py", line 98, in <module>
    os.system('7z a -ms=off ../%s-history.xml.7z %s-history.xml %s-titles.txt index.html Special:Version.html errors.log' % (prefix, prefix, prefix, prefix))
TypeError: not all arguments converted during string formatting

git-svn-id: https://wikiteam.googlecode.com/svn/trunk@778 31edc4fc-5e31-b4c4-d58b-c8bc928bcb95